CREATE TABLE `USERS` (
	`ID` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`USERNAME` text NOT NULL,
	`PASSWORD_HASH` text NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `USERS_USERNAME_unique` ON `USERS` (`USERNAME`);